apiVersion: v1
kind: Secret
metadata:
  name: maushold-secrets
  namespace: maushold
type: Opaque
stringData:
  DB_USER: "maushold"
  DB_PASSWORD: "maushold"
  REDIS_PASSWORD: "maushold"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"